### ISSUE TITLE
400 Client Error

### ISSUE THREAD

**Issue by mhy12345** [wy/namebase-exchange-python#8]
I use the following code...
```
exchange = Exchange(API_KEY, API_SECRET)
exchange.limit_buy(symbol = Symbol.HNSBTC, price = 0.00004687, quantity = 1.0, receive_window = None)
```
But the HTTPError raised
```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.namebase.io/api/v0/order
```

**Comment by wy** [comment]
Hi @mhy12345 - thanks for raising the issue. This is due to the way floats are being handled by the API downstream.
I've pushed a new version (0.0.6) and updated master, please use strings for price and quantity.
Also, I've exposed the underlying API error rather than the 400 for better explainability.
